services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dog
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: laravel
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    container_name: react
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

volumes: 
  mysql_data: